# Generated by Django 2.1.7 on 2019-03-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
