# Generated by Django 2.1.7 on 2019-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190328_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='created',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='result',
            field=models.CharField(default='', max_length=255),
        ),
    ]
