# Generated by Django 2.1.7 on 2019-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190328_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
