# Generated by Django 2.2 on 2019-07-03 16:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190329_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRecognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.path_and_rename)),
                ('result', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=api.models.path_and_rename),
        ),
    ]
